### ISSUE TITLE
 I have encountered some problems in compiling……

### ISSUE THREAD

**Issue by wty2019** [ktgiahieu/PPF-MEAM#3]
When I compile Makefile, the following error message appears：
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/PPF-MEAM-master/include/B2BTL_MEAM/B2BTL_MEAMRegistration.h:80:37: error: ‘shared_ptr’ does not name a type; did you mean ‘char16_t’?
       using FeatureHashMapTypePtr = shared_ptr<FeatureHashMapType>;
                                     ^~~~~~~~~~
                                     char16_t
/PPF-MEAM-master/include/B2BTL_MEAM/B2BTL_MEAMRegistration.h:262:45: error: ‘pcl::B2BTL_MEAMHashMapSearch::Ptr’ has not been declared
    setSearchMethod(B2BTL_MEAMHashMapSearch::Ptr search_method) { search_method_ = search_method; }
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I hope you can give us an answer. Thank you very much~

**Comment by ktgiahieu** [comment]
Yeah I'm sorry. The line should be "using FeatureHashMapTypePtr = std::shared_ptr <FeatureHashMapType>;"
I have also fixed other lines related to the missing prefix. 
Please re-clone the repo and rebuild to see if it works now.

**Comment by wty2019** [comment]
It works！
I tried to run the program several times, and though there were some segment fault,I finally got a successful result.
TOTAL 3D MATCHING TIME: 4917 mseconds.
thanks a lot.

**Comment by ktgiahieu** [comment]
There are some problems with VTK (for visualization) that creates segment fault, so far I have no idea how to fix it. If you disable the visualization there will be no errror. 
Great to see that it helps.
