### ISSUE TITLE
does it works for unorganized pointcloud

### ISSUE THREAD

**Issue by 965556810** [ktgiahieu/PPF-MEAM#4]
I'm not sure if these code works for unorganized pointcloud...  
if not . how to convert pointcloud from unorganized to organized

**Comment by ktgiahieu** [comment]
As this repo contains the processing steps of the journal, it is intended to be fed with the data retrieved from 3D cameras (such as Kinect, Realsense, DepthSense,etc). Therefore, the point cloud should be organized already.
To convert unorganized to organized ones, you need to know the camera parameters and the position of the camera coordinate, which is very unpractical, I believe.
