### ISSUE TITLE
HPR issues

### ISSUE THREAD

**Issue by chengm0-0** [ktgiahieu/PPF-MEAM#6]
Hi, thanks for your good job! It does work well in my system. I have some questions in the HPR.cpp, and I hope you can help me.
What is the meaning of these code？
        p = p - C.transpose().replicate(numPts, 1);   //maybe Convert points from camera coordinate system to world coordinate system？
	ArrayXd normp = (p*p).rowwise().sum().sqrt();  
	ArrayXd maxNormp(1); maxNormp << normp.maxCoeff()*pow(10,param); 
	ArrayXd R = maxNormp.replicate(numPts, 1);
	ArrayXXd P = p + 2 * (R - normp).replicate(1, dim) * p / normp.replicate(1, dim); 
Best wishes！

**Comment by ktgiahieu** [comment]
HPR stands for Hidden point removal, an algorithm proposed in the paper [Direct visibility of point sets](http://www.weizmann.ac.il/math/ronen/sites/math.ronen/files/uploads/katz_tal_basri_-_direct_visibility_of_point_sets.pdf) by Sagi Katz.
Here is the implementation from the author in MATLAB:
```
function visiblePtInds=HPR(p,C,param)
dim=size(p,2);
numPts=size(p,1);
% Move the points s.t. C is the origin
p=p-repmat(C,[numPts 1]);
% Calculate ||p||
normp=sqrt(dot(p,p,2));
% Sphere radius
R=repmat(max(normp)*(10ˆparam),[numPts 1]);
%Spherical flipping
P=p+2*repmat(R-normp,[1 dim]).*p./repmat(normp,[1 dim]);
%convex hull
visiblePtInds=unique(convhulln([P;zeros(1,dim)]));
visiblePtInds(visiblePtInds==numPts+1)=[];
```

With that said, these C++ code is just my take of the author's idea:
```
% Move the points s.t. C is the origin
p = p - C.transpose().replicate(numPts, 1);
% Calculate ||p||
ArrayXd normp = (p*p).rowwise().sum().sqrt();
% Sphere radius
ArrayXd maxNormp(1); maxNormp << normp.maxCoeff()*pow(10,param);
ArrayXd R = maxNormp.replicate(numPts, 1);
%Spherical flipping
ArrayXXd P = p + 2 * (R - normp).replicate(1, dim) * p / normp.replicate(1, dim);
%convex hull
.... (the rest of the file)
```

**Comment by chengm0-0** [comment]
Thanks for your answers! I think I have understood it!
