### ISSUE TITLE
code time-consuming problem

### ISSUE THREAD

**Issue by chengm0-0** [ktgiahieu/PPF-MEAM#7]
Hi， I have divided your code into offline and online by save the pointcloud as pcd file. But I found that when I use the online code, I import the pcd file, which cost about 60.3025s. Did you have met this question?
Thanks!

**Comment by ktgiahieu** [comment]
Since your question is pretty vague, I suggest that you time each line of code in the online stage. Then you should figure out which line is time-consuming, then save that variable in offline stage and load them in online stage.

**Comment by chengm0-0** [comment]
OK, thanks for your answer! I also want to get the pose of the object. So how can I do that in your code?

**Comment by ktgiahieu** [comment]
For detecting pose, you can see there are 2 main steps in my code, PPF.cpp file:
 - Using PPF, and the poses are in the variable `results`, line 248 :
```
typename pcl::MyPPFRegistration<pcl::PointNormal, pcl::PointNormal>::PoseWithVotesList results;
ppf_registration.computeFinalPoses(results);
```
you can access each pose with `results[results_i].pose`
 - Then align the poses with ICP for better result, and the pose is in the variable `transformation`, line 304 :
```
Eigen::Matrix4f transformation = icp.getFinalTransformation();
transformation = transformation * results[results_i].pose.matrix();
```

**Comment by chengm0-0** [comment]
Thanks for your help!

**Comment by chengm0-0** [comment]
Do you have the code for this article : Going Further with Point Pair Features ?Thanks!

**Comment by ktgiahieu** [comment]
Sorry I don't. You should try ask the author.
